### ISSUE TITLE
Add a exception when 403 Forbidden

### ISSUE THREAD

**Issue by gilles33377** [danpla/pindl#2]
Hi, when i download boards pindl stuck and stop work when 403 error. Can you make a exception or bypass the file?
(sorry for my bad english)

**Comment by danpla** [comment]
That's strange because the recent pindl bypasses any HTTP errors with ability to retry later.
What's your pindl version (`pindl.py -v`)?

**Comment by gilles33377** [comment]
1.1.0
The only way to bypass 403 Forbidden and download all is to change in line 351 :  if num_errors > 0: to if num_errors > 5: (for example)

**Comment by gilles33377** [comment]
Correction : I want to pass this file for example 
![forbidden](https://cloud.githubusercontent.com/assets/27515067/25527314/8e858df4-2c18-11e7-92b3-3d83bc09e5e1.JPG)

**Comment by danpla** [comment]
After a small investigation I found that the problem in the API: sometimes (or maybe always) URLs that point to PNG images have .jpg extensions. That's why you got 403 error. For example, for pin https://www.pinterest.com/pin/448811919102115238/ from your screenshot, the API returns the following URL, which will give you 403 error if you'll try to open it in your browser:

https://s-media-cache-ak0.pinimg.com/originals/13/d4/07/13d407b5281e340ad4d2838275311cd6.jpg

But if you'll change the extension to .png, all is OK.

I'll add a workaround soon.

**Comment by danpla** [comment]
The new v1.1.1 release is ready:

https://github.com/danpla/pindl/releases/latest

Thanks for the report!

**Comment by gilles33377** [comment]
Thanks ! I will try the new version soon.
