### ISSUE TITLE
Issues with non-ascii characters

### ISSUE THREAD

**Issue by eliblanco87** [danpla/pindl#5]
It seems to have problems with non-ascii characters, with the Win32 release on Windows 7:

```
$ ./pindl.exe -a ... https://www.pinterest.es/ticopicazo/natalia/
[5664] Failed to execute script pindl
Traceback (most recent call last):
  File "d:\pindl\pindl.py", line 531, in <module>
  File "d:\pindl\pindl.py", line 525, in main
  File "d:\pindl\pindl.py", line 372, in download_board
  File "d:\pindl\pindl.py", line 284, in printer
  File "C:\Python36-32\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 6-12: character maps to <undefined>

Natalia
by juan esteban
74 pins

 1/74 Rusia                                                  574138652487924709
 2/74 Natalya                                                574138652487922712
 3/74 ORTIZ ▒-Pintor Hiperrealista- Nace en Guadalajara, Ja▒ 574138652487914456
 4/74 Natalya                                                574138652487924702
```

**Comment by danpla** [comment]
I can't reproduce the issue on my Windows 7, so here are several questions:

* Are you using the EXE from https://github.com/danpla/pindl/releases (`pindl-1.1.3-win32.zip`) or it's
a custom EXE created with `win_dist.bat`?
* Is your Windows 32 or 64 bit?
* Are the latest Windows updates installed?
* Does running `chcp 65001` before `pindl.exe` fixes the issue?

**Comment by eliblanco87** [comment]
I used the win32 binary release, Win7 64bit with updates
However I didn't mention I run it on Cygwin... on normal cmd.exe it worked fine :)

**Comment by danpla** [comment]
I don't know why it fails with mintty (Cygwin's terminal emulator), but as I know Windows' console programs should be launched via `winpty` to work correctly. It's shipped with Git for Windows (Git Bash); for Cygwin, you have to install it manually. See https://github.com/rprichard/winpty.

![git-bash-mintty](https://user-images.githubusercontent.com/10910745/34570534-b9d4c584-f174-11e7-92e2-b42ff64ca80f.png)

Once you have `winpty`:

    winpty ./pindl.exe ...

This way it doesn't fail and correctly prints progress messages. Still, `winpty` automatically replaces `/` to `\`, so you will not be able to pass URLs as is. You can find workarounds for this behavior on the Internet, or use pindl's `-b` option to read URLs from a file.

Alternatively, you can simply ignore that error, because it's printed after all images are downloaded, or redirect stderr to `/dev/null`:

    ./pindl.exe ... 2> /dev/null

The best way, of course, is to use `cmd` or PowerShell.
